"""
network.py — Auto-generated by AutoArchitect
Problem:  detect illegal dumping in Oakland cameras and classify severity
Topology: sequential
Agents:   image → severity → report

Connection map:
#   image → severity  (output)
#   severity → report  (output)

This file connects all agents into a working network.
Generated by AutoArchitect AI — autoarchitect.ai
"""

import time, json
from pathlib import Path
from datetime import datetime

from agents.image_agent import ImageAgent
from agents.severity_agent import SeverityAgent
from agents.report_agent import ReportAgent


class AgentNetwork:
    """
    Autonomous agent network for: detect illegal dumping in Oakland cameras and classify sever
    Topology: sequential
    Agents: 3
    """

    def __init__(self):
        print("\n🕸️  Initializing Agent Network")
        print(f"   Problem:  detect illegal dumping in Oakland cameras and classify sever")
        print(f"   Topology: sequential")
        print(f"   Agents:   3\n")

        self.image = ImageAgent()
        self.severity = SeverityAgent()
        self.report = ReportAgent()

        self.processed  = set()
        self.total_runs = 0
        self.memory     = []
        print("✅ Network ready\n")

    def predict(self, input_data: str) -> dict:
        """Run input through all agents in sequential topology."""
        print(f"\n🔄 Processing: {Path(input_data).name}")
        self.total_runs += 1

        result = {}
        r_image = self.image.predict(input_data)
        self.image.act(r_image)
        result['image'] = r_image
        print(f"   [IMAGE] {r_image.get('label','?')} — {r_image.get('confidence',0):.0%}")
        r_severity = self.severity.predict(input_data)
        self.severity.act(r_severity)
        result['severity'] = r_severity
        print(f"   [SEVERITY] {r_severity.get('label','?')} — {r_severity.get('confidence',0):.0%}")
        r_report = self.report.predict(input_data)
        self.report.act(r_report)
        result['report'] = r_report
        print(f"   [REPORT] {r_report.get('label','?')} — {r_report.get('confidence',0):.0%}")
        return result

    def run(self, source: str = "input/", interval: int = 10):
        """
        Run network autonomously.
        Watches source folder, processes every new file.
        Gets smarter with every prediction.
        """
        src = Path(source)
        src.mkdir(parents=True, exist_ok=True)

        print(f"🚀 Network running autonomously")
        print(f"   Watching: {source}")
        print(f"   Interval: {interval}s")
        print(f"   Press Ctrl+C to stop\n")

        while True:
            try:
                new_files = [
                    f for f in src.iterdir()
                    if f.is_file() and str(f) not in self.processed
                ]
                if new_files:
                    for f in new_files:
                        result = self.predict(str(f))
                        self._log(f, result)
                        self.processed.add(str(f))
                    # Retrain if enough new examples
                    if len(self.processed) % 50 == 0:
                        self._retrain_all()
                else:
                    print(f"   👁️  Watching... ({len(self.processed)} processed)")
                time.sleep(interval)
            except KeyboardInterrupt:
                print("\n⛔ Network stopped")
                break

    def _retrain_all(self):
        print("\n🔄 Retraining all agents on accumulated memory...")
        for name in ['image', 'severity', 'report']:
            agent = getattr(self, name, None)
            if agent and hasattr(agent, "learn"):
                agent.learn()

    def _log(self, filepath, result: dict):
        log_file = Path("network_log.jsonl")
        entry = {
            "file":      filepath.name,
            "result":    result,
            "timestamp": datetime.now().isoformat(),
        }
        with open(log_file, "a") as f:
            f.write(json.dumps(entry) + "\n")

    def status(self) -> dict:
        return {
            "topology":   "sequential",
            "agents":     ['image', 'severity', 'report'],
            "total_runs": self.total_runs,
            "processed":  len(self.processed),
        }
