# ============================================
# AutoArchitect — Agent Generator
# Converts trained model → deployable agent
# User gets: agent.py + api_server.py + predict.py
# Zero ML knowledge needed to use
# ============================================

def generate_agent_code(problem: str,
                         category: str,
                         classes: list,
                         accuracy: float,
                         method: str,
                         agents_used: list) -> str:
    """Generate complete deployable agent.py"""

    classes_str  = str(classes)
    agents_str   = str(agents_used)
    is_image     = category in ('image', 'medical')
    is_text      = category in ('text', 'security')
    method_clean = method.replace('_', ' ').title()

    return f'''# ============================================
# AUTO-GENERATED by AutoArchitect AI
# Problem:  "{problem}"
# Category: {category}
# Method:   {method_clean}
# Accuracy: {accuracy}%
# Agents:   {agents_str}
# Classes:  {classes_str}
#
# Usage:
#   from agent import AutoArchitectAgent
#   agent = AutoArchitectAgent()
#   result = agent.predict("input_here")
#   print(result)
# ============================================

import os
import torch
import torch.nn as nn
import torch.nn.functional as F

# ── Configuration ────────────────────────────
PROBLEM   = "{problem}"
CATEGORY  = "{category}"
CLASSES   = {classes_str}
ACCURACY  = {accuracy}
METHOD    = "{method}"
MODEL_DIR = os.path.dirname(os.path.abspath(__file__))


class AutoArchitectAgent:
    """
    Deployable AI agent for: "{problem}"
    Trained accuracy: {accuracy}%
    Zero ML knowledge needed — just call predict()
    """

    def __init__(self, model_path: str = None):
        self.classes   = CLASSES
        self.category  = CATEGORY
        self.problem   = PROBLEM
        self.accuracy  = ACCURACY
        self.device    = torch.device("cpu")
        self.model     = None

        # Load model
        path = model_path or os.path.join(
            MODEL_DIR, "models", "agent_model.pth")
        if os.path.exists(path):
            self._load_model(path)
            print(f"✅ Agent loaded!")
            print(f"   Problem:  {{self.problem}}")
            print(f"   Accuracy: {{self.accuracy}}%")
            print(f"   Classes:  {{self.classes}}")
        else:
            print(f"⚠️  Model not found at: {{path}}")
            print(f"   Run: python run_nas.py first")

    def predict(self, input_data) -> dict:
        """
        Run prediction on new input.
        input_data: image path (str) OR PIL Image OR text (str)

        Returns:
            label:      predicted class name
            confidence: confidence percentage
            all_scores: scores for all classes
            action:     recommended action
        """
        if self.model is None:
            return {{"error": "Model not loaded",
                     "label": "unknown",
                     "confidence": 0}}

        try:
            if CATEGORY in ("image", "medical"):
                return self._predict_image(input_data)
            else:
                return self._predict_text(str(input_data))
        except Exception as e:
            return {{"error": str(e),
                     "label": "unknown",
                     "confidence": 0}}

    def predict_batch(self, inputs: list) -> list:
        """Run prediction on multiple inputs at once"""
        return [self.predict(inp) for inp in inputs]

    def info(self) -> dict:
        """Get agent information"""
        return {{
            "problem":   self.problem,
            "category":  self.category,
            "classes":   self.classes,
            "accuracy":  self.accuracy,
            "method":    METHOD,
            "ready":     self.model is not None,
        }}

    # ── Image Prediction ─────────────────────
    def _predict_image(self, input_data) -> dict:
        from PIL import Image
        import torchvision.transforms as T

        # Accept path or PIL Image
        if isinstance(input_data, str):
            img = Image.open(input_data).convert("RGB")
        elif hasattr(input_data, "convert"):
            img = input_data.convert("RGB")
        else:
            raise ValueError(
                "input_data must be image path or PIL Image")

        transform = T.Compose([
            T.Resize((224, 224)),
            T.ToTensor(),
            T.Normalize(
                mean=[0.485, 0.456, 0.406],
                std= [0.229, 0.224, 0.225])
        ])
        tensor = transform(img).unsqueeze(0).to(self.device)

        self.model.eval()
        with torch.no_grad():
            out   = self.model(tensor)
            probs = F.softmax(out, dim=1)[0]
            idx   = probs.argmax().item()
            conf  = round(probs.max().item() * 100, 1)

        label      = self.classes[idx] \
                     if idx < len(self.classes) \
                     else f"class_{{idx}}"
        all_scores = {{
            self.classes[i]: round(probs[i].item() * 100, 1)
            for i in range(min(len(self.classes), len(probs)))
        }}

        return {{
            "label":      label,
            "confidence": conf,
            "all_scores": all_scores,
            "action":     self._get_action(label, conf),
            "problem":    self.problem,
        }}

    # ── Text Prediction ──────────────────────
    def _predict_text(self, text: str) -> dict:
        # Simple bag-of-words approach
        # For production use DistilBERT
        vocab    = getattr(self, "_vocab", {{}})
        vec      = torch.zeros(1000)
        for word in text.lower().split():
            if word in vocab:
                vec[vocab[word]] += 1
        if vec.sum() > 0:
            vec = vec / vec.sum()

        tensor = vec.unsqueeze(0).to(self.device)

        self.model.eval()
        with torch.no_grad():
            out   = self.model(tensor)
            probs = F.softmax(out, dim=1)[0]
            idx   = probs.argmax().item()
            conf  = round(probs.max().item() * 100, 1)

        label      = self.classes[idx] \
                     if idx < len(self.classes) \
                     else f"class_{{idx}}"
        all_scores = {{
            self.classes[i]: round(probs[i].item() * 100, 1)
            for i in range(min(len(self.classes), len(probs)))
        }}

        return {{
            "label":      label,
            "confidence": conf,
            "all_scores": all_scores,
            "action":     self._get_action(label, conf),
            "problem":    self.problem,
        }}

    # ── Load Model ───────────────────────────
    def _load_model(self, path: str):
        checkpoint = torch.load(
            path,
            map_location=self.device,
            weights_only=False
        )
        n_classes = len(self.classes)

        if CATEGORY in ("image", "medical"):
            from torchvision.models import resnet18
            self.model    = resnet18(weights=None)
            self.model.fc = nn.Linear(512, n_classes)
        else:
            self.model = nn.Sequential(
                nn.Linear(1000, 256),
                nn.ReLU(),
                nn.Dropout(0.3),
                nn.Linear(256, 64),
                nn.ReLU(),
                nn.Linear(64, n_classes)
            )
            self._vocab = checkpoint.get("vocab", {{}})

        if "model_state" in checkpoint:
            self.model.load_state_dict(
                checkpoint["model_state"],
                strict=False)
        elif isinstance(checkpoint, dict) and \
             "state_dict" not in checkpoint:
            try:
                self.model.load_state_dict(
                    checkpoint, strict=False)
            except Exception:
                pass

        self.model = self.model.to(self.device)
        self.model.eval()

    # ── Action Recommendation ────────────────
    def _get_action(self, label: str,
                     confidence: float) -> str:
        label_lower = label.lower()
        conf_level  = (
            "High confidence" if confidence >= 80 else
            "Medium confidence" if confidence >= 60 else
            "Low confidence — consider more data"
        )

        # Domain-specific actions
        actions = {{
            "pothole":        "Schedule road repair — priority based on severity",
            "damage":         "Flag for inspection and maintenance",
            "spam":           "Move to spam folder — block sender",
            "fraud":          "Flag transaction — require manual review",
            "fake":           "Mark as unverified — do not share",
            "pneumonia":      "Consult physician immediately",
            "tumor":          "Urgent medical review required",
            "rotten":         "Remove from inventory — do not sell",
            "fresh":          "Clear for sale or consumption",
            "fire":           "Alert emergency services immediately",
            "attack":         "Isolate system — investigate immediately",
            "malware":        "Quarantine file — run full scan",
            "normal":         "No action required",
            "negative":       "Review and respond to feedback",
            "positive":       "Highlight as success case",
        }}

        for key, action in actions.items():
            if key in label_lower:
                return f"{{action}} ({{conf_level}})"

        return f"Classified as {{label}} — {{conf_level}}"


# ── CLI Entry Point ───────────────────────────
if __name__ == "__main__":
    import sys

    agent = AutoArchitectAgent()

    if not agent.model:
        print("Model not loaded. Run run_nas.py first.")
        sys.exit(1)

    if len(sys.argv) > 1:
        input_data = sys.argv[1]
        print(f"\\nPredicting: {{input_data}}")
        result = agent.predict(input_data)
        print(f"\\nResult:")
        print(f"  Label:      {{result['label']}}")
        print(f"  Confidence: {{result['confidence']}}%")
        print(f"  Action:     {{result['action']}}")
        if result.get("all_scores"):
            print(f"  All scores:")
            for cls, score in result["all_scores"].items():
                bar = "█" * int(score / 5)
                print(f"    {{cls:<20}} {{bar}} {{score}}%")
    else:
        print("\\nUsage: python agent.py <image_path_or_text>")
        print("Example:")
        if CATEGORY in ("image", "medical"):
            print("  python agent.py photo.jpg")
        else:
            print('  python agent.py "this email looks suspicious"')
        print(f"\\nAgent info: {{agent.info()}}")
'''


def generate_api_server() -> str:
    """Generate Flask API wrapper for the agent"""
    return '''# ============================================
# AUTO-GENERATED by AutoArchitect AI
# REST API wrapper for your trained agent
#
# Run:  python api_server.py
# Test: curl -X POST http://localhost:5001/predict
#       -F "file=@your_image.jpg"
# ============================================

from flask import Flask, request, jsonify
from agent import AutoArchitectAgent
import io
import os

app   = Flask(__name__)
agent = AutoArchitectAgent()

@app.route("/", methods=["GET"])
def home():
    return jsonify({
        "service":  "AutoArchitect Agent API",
        "problem":  agent.problem,
        "accuracy": agent.accuracy,
        "classes":  agent.classes,
        "endpoints": {
            "POST /predict":       "predict from file upload",
            "POST /predict/text":  "predict from text",
            "GET  /info":          "agent information",
            "GET  /health":        "health check",
        }
    })

@app.route("/predict", methods=["POST"])
def predict():
    """Predict from uploaded image or text file"""
    if "file" in request.files:
        from PIL import Image
        f   = request.files["file"]
        img = Image.open(io.BytesIO(f.read()))
        return jsonify(agent.predict(img))

    if "text" in request.form:
        return jsonify(agent.predict(request.form["text"]))

    if request.is_json:
        data = request.get_json()
        if "text" in data:
            return jsonify(agent.predict(data["text"]))

    return jsonify({"error": "Send file or text"}), 400

@app.route("/predict/text", methods=["POST"])
def predict_text():
    """Predict from raw text"""
    data = request.get_json() or {}
    text = data.get("text", "")
    if not text:
        return jsonify({"error": "No text provided"}), 400
    return jsonify(agent.predict(text))

@app.route("/predict/batch", methods=["POST"])
def predict_batch():
    """Predict multiple inputs at once"""
    files   = request.files.getlist("files")
    results = []
    for f in files:
        from PIL import Image
        img = Image.open(io.BytesIO(f.read()))
        results.append({
            "filename": f.filename,
            "result":   agent.predict(img)
        })
    return jsonify({"results": results, "count": len(results)})

@app.route("/info", methods=["GET"])
def info():
    return jsonify(agent.info())

@app.route("/health", methods=["GET"])
def health():
    return jsonify({
        "status": "healthy" if agent.model else "model_not_loaded",
        "ready":  agent.model is not None
    })

if __name__ == "__main__":
    print("=" * 50)
    print("  AutoArchitect Agent API")
    print(f"  Problem:  {agent.problem}")
    print(f"  Accuracy: {agent.accuracy}%")
    print(f"  Classes:  {agent.classes}")
    print("=" * 50)
    print("  Endpoints:")
    print("  POST http://localhost:5001/predict")
    print("  GET  http://localhost:5001/info")
    print("=" * 50)
    app.run(host="0.0.0.0", port=5001, debug=False)
'''


def generate_predict_cli(problem: str,
                          category: str,
                          classes: list) -> str:
    """Generate simple CLI predict script"""
    is_image = category in ('image', 'medical')
    example  = "road_photo.jpg" if is_image \
               else "suspicious_email.txt"
    usage    = f'python predict.py {example}' if is_image \
               else f'python predict.py "your text here"'

    return f'''# ============================================
# AUTO-GENERATED by AutoArchitect AI
# Simple predictor for: "{problem}"
#
# Usage: {usage}
# ============================================

import sys
from agent import AutoArchitectAgent

def main():
    if len(sys.argv) < 2:
        print("Usage: {usage}")
        print("Classes: {classes}")
        sys.exit(1)

    agent  = AutoArchitectAgent()
    inp    = sys.argv[1]
    result = agent.predict(inp)

    print("\\n" + "="*50)
    print(f"  Result: {{result['label'].upper()}}")
    print(f"  Confidence: {{result['confidence']}}%")
    print(f"  Action: {{result['action']}}")
    print("="*50)

    if result.get("all_scores"):
        print("\\nAll class scores:")
        for cls, score in sorted(
                result["all_scores"].items(),
                key=lambda x: x[1], reverse=True):
            bar = "█" * int(score / 5) + "░" * (20 - int(score/5))
            print(f"  {{cls:<20}} {{bar}} {{score:.1f}}%")

    return result

if __name__ == "__main__":
    main()
'''


def generate_readme(problem: str,
                     category: str,
                     classes: list,
                     accuracy: float,
                     method: str,
                     agents_used: list) -> str:
    """Generate clear README"""
    is_image = category in ('image', 'medical')
    example  = "road_photo.jpg" if is_image \
               else '"this message looks suspicious"'

    return f'''# AutoArchitect Agent
## Trained for: "{problem}"

| Property | Value |
|----------|-------|
| Accuracy | {accuracy}% |
| Method   | {method.replace("_", " ").title()} |
| Classes  | {classes} |
| Agents   | {agents_used} |

---

## Quick Start (3 steps)

### 1. Install
```bash
pip install -r requirements.txt
```

### 2. Predict immediately
```bash
python predict.py {example}
```

### 3. Use in your project
```python
from agent import AutoArchitectAgent

agent  = AutoArchitectAgent()
result = agent.predict("{example.strip(chr(34))}")

print(result["label"])       # → {classes[0] if classes else "class"}
print(result["confidence"])  # → 87.4
print(result["action"])      # → recommended action
```

---

## Deploy as REST API

```bash
python api_server.py
# Running on http://localhost:5001
```

```bash
# Test with curl
curl -X POST http://localhost:5001/predict \\
     -F "file=@your_image.jpg"

# Response:
# {{"label": "{classes[0] if classes else 'result'}", "confidence": 87.4, "action": "..."}}
```

---

## All Classes
{chr(10).join(f"- `{c}`" for c in classes)}

---

## Built with AutoArchitect AI
- Oakland Research Showcase 2026
- Multi-Agent NAS + Meta-Learning Brain
- $0 infrastructure cost
'''


def generate_requirements() -> str:
    return """torch
torchvision
Pillow
flask
flask-cors
numpy
"""